services:
  namenode:
    image: gelog/hadoop
    ports: ["50070:50070"]
    command: hdfs namenode
    hostname: hdfs-namenode
    networks: [hadoop]

  datanode:
    image: gelog/hadoop
    command: hdfs datanode
    ports: ["50075"]
    # links: ["namenode:hdfs-namenode"]
    networks: [hadoop]

  secondarynamenode:
    image: gelog/hadoop
    command: hdfs secondarynamenode
    ports: ["50090:50090"]
    # links: [namenode:hdfs-namenode]
    networks: [hadoop]

  yarn:
    image: gelog/hadoop
    ports: ["8088:8088", "8042:8042"] # [resource manager, node manager]
    command: start-yarn.sh
    hostname: yarn
    networks: [hadoop]
    # volumes:
    #   - $HOME/data/hadoop/hdfs:/data
  
networks:
  hadoop:
    driver: bridge